package Visao;

import Control.ControlProfessor;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author oliveira kiala
 */
public class Interface extends javax.swing.JFrame {

    

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        PainelPrincipal1 = new javax.swing.JDesktopPane();
        BarraMenu1 = new javax.swing.JMenuBar();
        Menucadastro1 = new javax.swing.JMenu();
        MenuItemCadastroProfessor1 = new javax.swing.JMenuItem();
        MenuItemCadastroAcademico2 = new javax.swing.JMenuItem();
        Menurelatorio2 = new javax.swing.JMenu();
        MenuItemRelatorioProfessor3 = new javax.swing.JMenuItem();
        MenuItemRelatorioAcademico4 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento Escolar");

        javax.swing.GroupLayout PainelPrincipal1Layout = new javax.swing.GroupLayout(PainelPrincipal1);
        PainelPrincipal1.setLayout(PainelPrincipal1Layout);
        PainelPrincipal1Layout.setHorizontalGroup(
            PainelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        PainelPrincipal1Layout.setVerticalGroup(
            PainelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        Menucadastro1.setText("Cadastro   |");

        MenuItemCadastroProfessor1.setText("Professor");
        MenuItemCadastroProfessor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCadastroProfessor1ActionPerformed(evt);
            }
        });
        Menucadastro1.add(MenuItemCadastroProfessor1);

        MenuItemCadastroAcademico2.setText("Acadêmico");
        MenuItemCadastroAcademico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCadastroAcademico2ActionPerformed(evt);
            }
        });
        Menucadastro1.add(MenuItemCadastroAcademico2);

        BarraMenu1.add(Menucadastro1);

        Menurelatorio2.setText("Relatório");

        MenuItemRelatorioProfessor3.setText("Professor");
        MenuItemRelatorioProfessor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemRelatorioProfessor3ActionPerformed(evt);
            }
        });
        Menurelatorio2.add(MenuItemRelatorioProfessor3);

        MenuItemRelatorioAcademico4.setText("Acadêmico");
        Menurelatorio2.add(MenuItemRelatorioAcademico4);

        BarraMenu1.add(Menurelatorio2);

        setJMenuBar(BarraMenu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal1)
        );

        setSize(new java.awt.Dimension(685, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemCadastroProfessor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCadastroProfessor1ActionPerformed
        CadastroProfessor objeto = new CadastroProfessor();
        PainelPrincipal1.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_MenuItemCadastroProfessor1ActionPerformed

    private void MenuItemRelatorioProfessor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemRelatorioProfessor3ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_MenuItemRelatorioProfessor3ActionPerformed

    private void MenuItemCadastroAcademico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCadastroAcademico2ActionPerformed
        CadastroAcademico objeto = new CadastroAcademico();
        PainelPrincipal1.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_MenuItemCadastroAcademico2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu1;
    private javax.swing.JMenuItem MenuItemCadastroAcademico2;
    private javax.swing.JMenuItem MenuItemCadastroProfessor1;
    private javax.swing.JMenuItem MenuItemRelatorioAcademico4;
    private javax.swing.JMenuItem MenuItemRelatorioProfessor3;
    private javax.swing.JMenu Menucadastro1;
    private javax.swing.JMenu Menurelatorio2;
    private javax.swing.JDesktopPane PainelPrincipal1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    // End of variables declaration//GEN-END:variables
}
